#:kivy 1.0.9

Appspace:
	Workspace:

<Workspace>:
	orientation: 'horizontal'

#	Button:
#		size_hint: (1, .2)
#		pos_hint: {'x':0, 'y':0}
#		text: "print code to console"
#		on_press: print root.codespace.getWholeText()

<Splitter>: 
	sizable_from: 'right'
	pos_hint: {'top': 1, 'x': 0}


# for debugging purposes
#<Widget>:
#    canvas.after:
#       Line:
#            rectangle: self.x+1,self.y+1,self.width-1,self.height-1
#            dash_offset: 5
#            dash_length: 3